# 项目基础设置
server:
  port: 8088
  servlet:
    context-path: /yby
  tomcat:
    uri-encoding: UTF-8
    # 最大工作线程数 默认200
    max-thread: 800
    # 最大连接数
    max-connections: 2000
    # 最小工作空闲线程数 默认数10
    min-spare-threads: 30

# spring 相关
spring:
  datasource:
    ship:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      username: root
      password: password111
      type: com.zaxxer.hikari.HikariDataSource
      initialization-mode: always
      continue-on-error: true
  hikari:
    minimum-idle: 5
    connection-test-query: SELECT 1 FROM DUAL
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 30000
    pool-name: SpringBootHikariCP
    max-lifetime: 60000
    connection-timeout: 30000
